[INFO][2020-08-26 12:18:25,763][autoreload.py:598]Watching for file changes with StatReloader
[DEBUG][2020-08-26 12:18:48,861][selector_events.py:53]Using selector: KqueueSelector
[WARNING][2020-08-26 12:19:15,450][log.py:228]Not Found: /runtask/1
[INFO][2020-08-26 12:19:44,051][views.py:63]vW2zQJyMQoCIFfXN5gb5BLNMbJui8q1598415584
[ERROR][2020-08-26 12:19:44,886][log.py:228]Internal Server Error: /tasks/run/1
Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/apps/tasks/views.py", line 64, in post
    celery_task_id = run_task.delay(taskid, jmxs, task_flow_str)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type QuerySet is not JSON serializable
[INFO][2020-08-26 12:20:05,374][views.py:63]GPuwLOUtPAyPuRdCuiBUEgcqL6Ty9g1598415605
[ERROR][2020-08-26 12:20:05,731][log.py:228]Internal Server Error: /tasks/run/1
Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/apps/tasks/views.py", line 64, in post
    celery_task_id = run_task.delay(taskid, jmxs, task_flow_str)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type QuerySet is not JSON serializable
[INFO][2020-08-26 12:21:45,970][autoreload.py:222]/Users/chenlei/python-project/jmeter_platform/apps/tasks/tasks.py changed, reloading.
[DEBUG][2020-08-26 12:21:45,972][selector_events.py:53]Using selector: KqueueSelector
[INFO][2020-08-26 12:21:47,611][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-26 12:21:49,447][autoreload.py:222]/Users/chenlei/python-project/jmeter_platform/apps/tasks/tasks.py changed, reloading.
[DEBUG][2020-08-26 12:21:49,449][selector_events.py:53]Using selector: KqueueSelector
[INFO][2020-08-26 12:21:50,100][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-26 12:22:20,329][views.py:63]bYcU4oILwNZjlcQXqvLF5Jo1xX1mna1598415740
[ERROR][2020-08-26 12:22:21,240][log.py:228]Internal Server Error: /tasks/run/1
Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/apps/tasks/views.py", line 64, in post
    celery_task_id = run_task.delay(taskid, jmxs, task_flow_str)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type QuerySet is not JSON serializable
[DEBUG][2020-08-26 12:22:35,724][selector_events.py:53]Using selector: KqueueSelector
[INFO][2020-08-26 12:22:42,758][views.py:63]62d6SijOicwlOUAELFwiRNLjCG82ki1598415762
[ERROR][2020-08-26 12:22:43,105][log.py:228]Internal Server Error: /tasks/run/1
Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/apps/tasks/views.py", line 64, in post
    celery_task_id = run_task.delay(taskid, jmxs, task_flow_str)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type QuerySet is not JSON serializable
[INFO][2020-08-26 12:25:33,646][autoreload.py:222]/Users/chenlei/python-project/jmeter_platform/apps/tasks/tasks.py changed, reloading.
[DEBUG][2020-08-26 12:25:33,654][selector_events.py:53]Using selector: KqueueSelector
[INFO][2020-08-26 12:25:35,586][autoreload.py:598]Watching for file changes with StatReloader
[DEBUG][2020-08-26 12:25:41,778][selector_events.py:53]Using selector: KqueueSelector
[INFO][2020-08-26 12:26:18,112][views.py:63]grSYOIPgRa2jL5DA94fd3ttUIZmRbO1598415978
[ERROR][2020-08-26 12:26:19,052][log.py:228]Internal Server Error: /tasks/run/1
Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/apps/tasks/views.py", line 64, in post
    celery_task_id = run_task.delay(taskid, jmxs, task_flow_str)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/chenlei/python-project/jmeter_platform/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type QuerySet is not JSON serializable
[DEBUG][2020-08-26 12:26:54,690][selector_events.py:53]Using selector: KqueueSelector
